/**
 * Voice profile distiller.
 *
 *   npm run init-voice           (from backend/)   — or:  npm run init-voice  (from root)
 *
 * Reads the real messages you've dropped into voice_profile/raw_corpus/ (plus
 * linkedin_successful_messages.md if present) and asks your configured LLM to
 * distill them into voice_profile/strategy_analysis.md — the single file the
 * assistant uses to sound like you.
 *
 * Safety: never overwrites an existing strategy_analysis.md. If one exists, the
 * draft is written to strategy_analysis.draft.md for you to review and rename.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { runLLM } from "./llm/index.js";
import { ensureWorkspace } from "./workspace.js";
import { readFeedback } from "./feedback.js";

const VOICE_DIR = resolve(process.cwd(), "..", "voice_profile");
const RAW_DIR = join(VOICE_DIR, "raw_corpus");
const CORPUS_FILE = join(VOICE_DIR, "linkedin_successful_messages.md");
const OUT = join(VOICE_DIR, "strategy_analysis.md");
const DRAFT = join(VOICE_DIR, "strategy_analysis.draft.md");

// Keep the prompt small so the call is fast and reliable across providers.
// A few hundred sample messages fit easily; more than this adds latency
// without improving the distillation.
const MAX_CHARS = 20_000;

const INSTRUCTION = [
  "You are analysing a person's REAL past messages to capture how they write, so",
  "an assistant can draft new messages in their exact voice.",
  "Do NOT use any tools — analyse only the samples provided below.",
  "",
  "Read the samples and produce a Markdown document titled '# Strategy analysis —",
  "voice profile'. Use these sections, and under each write 1–3 SPECIFIC, concrete",
  "observations grounded in the samples (quote short fragments where useful):",
  "",
  "  - How I open messages",
  "  - Sentence length and rhythm",
  "  - How I disagree",
  "  - How I ask questions",
  "  - Vocabulary I avoid",
  "  - How I close",
  "  - Register shifts (who gets a warmer vs. more formal tone)",
  "  - How I decline things",
  "  - Example phrasings I actually use",
  "",
  "Be precise, not generic — 'opens with a one-line acknowledgement, no greeting'",
  "beats 'friendly and professional'.",
  "If a CORRECTIONS section is present, honour those preferences and let them",
  "override the raw samples where they conflict. Output ONLY the Markdown document,",
  "nothing else.",
].join("\n");

function collectRaw(): { text: string; fileCount: number } {
  const parts: string[] = [];
  let fileCount = 0;

  if (existsSync(RAW_DIR)) {
    for (const name of readdirSync(RAW_DIR)) {
      if (name.startsWith(".")) continue;
      if (name.toLowerCase() === "readme.md") continue;
      const p = join(RAW_DIR, name);
      try {
        const body = readFileSync(p, "utf-8").trim();
        if (body) {
          parts.push(`### from ${name}\n${body}`);
          fileCount++;
        }
      } catch {
        /* skip unreadable file */
      }
    }
  }

  if (existsSync(CORPUS_FILE)) {
    const body = readFileSync(CORPUS_FILE, "utf-8").trim();
    if (body) {
      parts.push(`### from linkedin_successful_messages.md\n${body}`);
      fileCount++;
    }
  }

  return { text: parts.join("\n\n---\n\n").trim(), fileCount };
}

async function main(): Promise<void> {
  if (!existsSync(VOICE_DIR)) mkdirSync(VOICE_DIR, { recursive: true });

  const { text, fileCount } = collectRaw();
  if (!text) {
    console.error(
      "No source messages found.\n\n" +
        `Put a few of your real sent messages (LinkedIn DMs, emails, …) into:\n` +
        `  ${RAW_DIR}\n` +
        "then run this again. (linkedin_successful_messages.md is also picked up if present.)",
    );
    process.exit(1);
  }

  const clipped = text.length > MAX_CHARS;
  let context =
    "=== MY REAL PAST MESSAGES (samples to learn my voice from) ===\n" +
    (clipped ? text.slice(0, MAX_CHARS) + "\n…(truncated)" : text);

  // Fold in any corrections captured via 👍/👎 in the overlay.
  const feedback = readFeedback();
  if (feedback) {
    context +=
      "\n\n=== CORRECTIONS I'VE FLAGGED (apply these — they override the samples where they conflict) ===\n" +
      feedback.slice(0, 8_000);
  }

  console.log(
    `Found ${fileCount} source file(s)${clipped ? " (truncated to fit)" : ""}. ` +
      "Distilling your voice profile via the configured LLM — this can take up to a minute…",
  );

  ensureWorkspace(); // gemini-cli needs its sandbox cwd to exist
  const res = await runLLM(INSTRUCTION, context);

  const body =
    "<!-- Generated by `npm run init-voice` from voice_profile/raw_corpus/. " +
    "Review and edit — this is the single file the assistant uses to match your voice. -->\n\n" +
    res.text.trim() +
    "\n";

  const wroteDraft = existsSync(OUT);
  const target = wroteDraft ? DRAFT : OUT;
  writeFileSync(target, body, "utf-8");

  console.log(`\n✓ Wrote ${target}`);
  if (wroteDraft) {
    console.log(
      "strategy_analysis.md already existed, so I saved a draft instead.\n" +
        "Compare them and rename the draft over the original if you prefer it.",
    );
  } else {
    console.log(
      "This is now your runtime voice profile. Open it, fix anything that's off,\n" +
        "then start the backend with `npm start`.",
    );
  }
}

main().catch((err) => {
  console.error("\ninit-voice failed:", (err as Error).message);
  console.error(
    "Check that your LLM is configured in backend/.env (provider + key if needed).",
  );
  process.exit(1);
});
