/**
 * Shared voice-distillation logic.
 *
 * The corpus-collection + LLM-distillation that used to live inline in
 * initVoice.ts, extracted here so the CLI (`initVoice.ts`) AND the future HTTP
 * endpoints (`POST /voice/distill`, per-section regenerate) share one
 * implementation. Everything is tenant-aware: the local tenant keeps its
 * repo-root `voice_profile/`, other tenants resolve under
 * `backend/data/tenants/<id>/voice_profile/` — both via `voiceDirFor`.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { runLLM } from "./llm/index.js";
import { ensureWorkspace } from "./workspace.js";
import { DEFAULT_TENANT } from "./tenant.js";
import { voiceDirFor } from "./voiceProfile.js";
import { SECTION_LABELS, type SectionKey } from "./voiceSections.js";

// Keep the prompt small so the call is fast and reliable across providers.
// A few hundred sample messages fit easily; more than this adds latency
// without improving the distillation.
const MAX_CHARS = 20_000;

/** The distillation instruction the LLM analyses the corpus with. */
export const DISTILL_INSTRUCTION = [
  "You are analysing a person's REAL past messages to capture how they write, so",
  "an assistant can draft new messages in their exact voice.",
  "Do NOT use any tools — analyse only the samples provided below.",
  "",
  "Read the samples and produce a Markdown document titled '# Strategy analysis —",
  "voice profile'. Use these sections, and under each write 1–3 SPECIFIC, concrete",
  "observations grounded in the samples (quote short fragments where useful):",
  "",
  "  - How I open messages",
  "  - Sentence length and rhythm",
  "  - How I disagree",
  "  - How I ask questions",
  "  - Vocabulary I avoid",
  "  - How I close",
  "  - Register shifts (who gets a warmer vs. more formal tone)",
  "  - How I decline things",
  "  - Example phrasings I actually use",
  "",
  "Be precise, not generic — 'opens with a one-line acknowledgement, no greeting'",
  "beats 'friendly and professional'.",
  "If a CORRECTIONS section is present, honour those preferences and let them",
  "override the raw samples where they conflict. Output ONLY the Markdown document,",
  "nothing else.",
].join("\n");

/**
 * Read a tenant's raw corpus: every file under `raw_corpus/` plus the
 * `linkedin_successful_messages.md` companion, concatenated with separators.
 * Returns the joined text and how many source files contributed.
 */
export function collectCorpus(tenantId: string = DEFAULT_TENANT): {
  text: string;
  fileCount: number;
} {
  const voiceDir = voiceDirFor(tenantId);
  const rawDir = join(voiceDir, "raw_corpus");
  const corpusFile = join(voiceDir, "linkedin_successful_messages.md");

  const parts: string[] = [];
  let fileCount = 0;

  if (existsSync(rawDir)) {
    for (const name of readdirSync(rawDir)) {
      if (name.startsWith(".")) continue;
      if (name.toLowerCase() === "readme.md") continue;
      const p = join(rawDir, name);
      try {
        const body = readFileSync(p, "utf-8").trim();
        if (body) {
          parts.push(`### from ${name}\n${body}`);
          fileCount++;
        }
      } catch {
        /* skip unreadable file */
      }
    }
  }

  if (existsSync(corpusFile)) {
    const body = readFileSync(corpusFile, "utf-8").trim();
    if (body) {
      parts.push(`### from linkedin_successful_messages.md\n${body}`);
      fileCount++;
    }
  }

  return { text: parts.join("\n\n---\n\n").trim(), fileCount };
}

/** The provenance header prepended to every distilled profile. */
const GENERATED_HEADER =
  "<!-- Generated by `npm run init-voice` from voice_profile/raw_corpus/. " +
  "Review and edit — this is the single file the assistant uses to match your voice. -->\n\n";

/**
 * Distill a tenant's voice profile. Builds the LLM context (the real past
 * messages, plus an optional CORRECTIONS block) and returns the resulting
 * Markdown body — with the `<!-- Generated… -->` header — but does NOT write
 * any file; callers decide where it lands.
 *
 * @param opts.corpusText  use this corpus instead of reading `raw_corpus/`
 *                         (e.g. a paste from the dashboard). When omitted the
 *                         tenant's on-disk corpus is collected.
 * @param opts.feedback    optional corrections to fold in (overrides samples).
 */
export async function distill(
  tenantId: string = DEFAULT_TENANT,
  opts?: { corpusText?: string; feedback?: string },
): Promise<string> {
  const text = (opts?.corpusText ?? collectCorpus(tenantId).text).trim();

  const clipped = text.length > MAX_CHARS;
  let context =
    "=== MY REAL PAST MESSAGES (samples to learn my voice from) ===\n" +
    (clipped ? text.slice(0, MAX_CHARS) + "\n…(truncated)" : text);

  // Fold in any corrections captured via 👍/👎 in the overlay.
  if (opts?.feedback) {
    context +=
      "\n\n=== CORRECTIONS I'VE FLAGGED (apply these — they override the samples where they conflict) ===\n" +
      opts.feedback.slice(0, 8_000);
  }

  ensureWorkspace(tenantId); // gemini-cli needs its sandbox cwd to exist
  const res = await runLLM(DISTILL_INSTRUCTION, context, { tenantId });

  return GENERATED_HEADER + res.text.trim() + "\n";
}

/**
 * The one aspect each section asks the model to focus on. Used to build a
 * section-specific instruction for `distillSection` — the per-section analogue
 * of the nine bullets baked into DISTILL_INSTRUCTION above.
 */
const SECTION_FOCUS: Record<SectionKey, string> = {
  openers: "how I OPEN messages (greeting or not, first line)",
  rhythm: "my sentence length and rhythm",
  disagreeing: "how I DISAGREE or push back",
  questions: "how I ask questions",
  closings: "how I CLOSE/sign off",
  registers: "how my tone shifts by audience (who gets warmer vs. more formal)",
  vocabulary: "words/phrases I use and ones I avoid",
  declining: "how I decline or say no",
};

/**
 * Regenerate a SINGLE voice-profile section from the corpus — the per-card
 * "Regenerate this section" action. Same corpus/clipping as `distill()`, but
 * the model is told to analyse ONLY the one aspect named by `key` and return
 * just that section's body (no Markdown heading, no preamble) — ready to drop
 * straight into `saveSection(tenantId, key, body)`.
 *
 * @param opts.corpusText  use this corpus instead of reading `raw_corpus/`.
 * @throws if the corpus is empty — there are no samples to learn from.
 */
export async function distillSection(
  tenantId: string,
  key: SectionKey,
  opts?: { corpusText?: string },
): Promise<string> {
  const text = (opts?.corpusText ?? collectCorpus(tenantId).text).trim();
  if (!text) {
    throw new Error(
      `Cannot regenerate section "${key}": no voice corpus found for tenant "${tenantId}".`,
    );
  }

  const clipped = text.length > MAX_CHARS;
  const context =
    "=== MY REAL PAST MESSAGES (samples to learn my voice from) ===\n" +
    (clipped ? text.slice(0, MAX_CHARS) + "\n…(truncated)" : text);

  const sectionInstruction = [
    "You are analysing a person's REAL past messages to capture how they write, so",
    "an assistant can draft new messages in their exact voice.",
    "Do NOT use any tools — analyse only the samples provided below.",
    "",
    `Focus on ONE aspect only: ${SECTION_FOCUS[key]} (the "${SECTION_LABELS[key]}" section).`,
    "Write 1–4 SPECIFIC, concrete observations grounded in the samples (quote short",
    "fragments where useful) as plain prose or bullets. Be precise, not generic —",
    "'opens with a one-line acknowledgement, no greeting' beats 'friendly and professional'.",
    "",
    "Output ONLY the body text for that one section — NO Markdown heading, NO preamble,",
    "no other sections, nothing else.",
  ].join("\n");

  ensureWorkspace(tenantId); // gemini-cli needs its sandbox cwd to exist
  const res = await runLLM(sectionInstruction, context, { tenantId });

  return res.text.trim();
}
